import { Locale } from './models';

export type Dictionary = typeof dictionaries.mn;

export const dictionaries = {
  mn: {
    siteName: 'Rare Care',
    languageLabel: 'MN',
    alternateLanguageLabel: 'EN',
    nav: {
      accessibility: 'Хүртээмж',
      events: 'Арга хэмжээ',
      dailyCorner: 'Өдрийн булан',
      contact: 'Холбоо барих',
      diseaseInformation: 'Өвчний мэдээлэл',
      community: 'Олон нийт',
      donate: 'Хандив',
      searchPlaceholder: 'Өвчнөөр хайх...',
    },
    common: {
      home: 'Нүүр',
      siteRegion: 'Монгол',
      learnMore: 'Дэлгэрэнгүй',
      readNow: 'Унших',
      joinGroup: 'Нэгдэх',
      applyNow: 'Хүсэлт илгээх',
      makeDonation: 'Хандив өргөх',
      upcomingEvents: 'Удахгүй болох арга хэмжээ',
      everydayTips: 'Өдөр тутмын зөвлөгөө',
      educationalDisclaimer:
        'Энэ хэсгийн мэдээлэл нь боловсролын зориулалттай бөгөөд эмчийн мэргэжлийн зөвлөгөөг орлохгүй.',
      noResults: 'Тохирох мэдээлэл олдсонгүй.',
      audio: 'Аудио хувилбар',
      submit: 'Илгээх',
      sending: 'Илгээж байна...',
      search: 'Хайх',
      reset: 'Арилгах',
      other: 'Бусад',
      openMenu: 'Цэс нээх',
      closeMenu: 'Цэс хаах',
      submitError: 'Илгээх үед алдаа гарлаа.',
      generalError: 'Алдаа гарлаа',
      postedOn: 'Огноо',
      allCategories: 'Бүх ангилал',
      notFound: 'Хуудас эсвэл мэдээлэл олдсонгүй.',
    },
    auth: {
      account: 'Бүртгэл',
      login: 'Нэвтрэх',
      register: 'Бүртгүүлэх',
      profile: 'Профайл',
      logout: 'Гарах',
      signedInAs: 'Нэвтэрсэн хэрэглэгч',
      welcomeTitle: 'Rare Care-д тавтай морил',
      welcomeBody: 'Өөрийн бүртгэлээр нэвтэрч хадгалсан оролцоо, цаашдын дэмжлэгийн боломжууддаа холбогдоорой.',
      loginTitle: 'Нэвтрэх',
      loginBody: 'Имэйл болон нууц үгээрээ аюулгүй нэвтэрнэ үү.',
      registerTitle: 'Бүртгэл үүсгэх',
      registerBody: 'Энгийн бүртгэл үүсгээд Rare Care-ийн ирээдүйн дэмжлэгийн боломжуудтай холбогдоорой.',
      name: 'Нэр',
      email: 'Имэйл',
      password: 'Нууц үг',
      confirmPassword: 'Нууц үгээ давтана уу',
      createAccount: 'Бүртгэл үүсгэх',
      close: 'Хаах',
      passwordHint: 'Нууц үг хамгийн багадаа 8 тэмдэгт байна.',
      emailRequired: 'Имэйлээ оруулна уу.',
      emailInvalid: 'Зөв имэйл хаяг оруулна уу.',
      nameRequired: 'Нэрээ оруулна уу.',
      nameMinLength: 'Нэр хамгийн багадаа 2 тэмдэгт байна.',
      passwordRequired: 'Нууц үгээ оруулна уу.',
      passwordMinLength: 'Нууц үг хамгийн багадаа 8 тэмдэгт байна.',
      confirmPasswordRequired: 'Нууц үгээ дахин оруулна уу.',
      passwordMismatch: 'Нууц үгүүд таарахгүй байна.',
      loginCta: 'Одоо нэвтрэх',
      registerCta: 'Шинэ бүртгэл',
    },
    profile: {
      title: 'Профайл',
      body: 'Өөрийн нэр, зураг, бүртгэлийн мэдээллээ энэ хэсгээс хянаарай.',
      photoUpload: 'Профайл зураг оруулах',
      photoHelp: 'Зурагтай файл сонгоно уу. JPG, PNG зэрэг ердийн зураг ажиллана.',
      photoPreview: 'Зургийн харагдац',
      removePhoto: 'Зураг арилгах',
      photoTypeError: 'Зөвхөн зураг файл оруулна уу.',
      photoSizeError: 'Зургийн хэмжээ хэт том байна. 4MB-аас бага файл сонгоно уу.',
      emailReadonly: 'Имэйл хаягийг одоогоор зөвхөн харах боломжтой.',
      memberSince: 'Элссэн огноо',
      save: 'Профайл хадгалах',
      success: 'Профайл амжилттай шинэчлэгдлээ.',
      signedOutTitle: 'Профайлд нэвтрэх шаардлагатай',
      signedOutBody:
        'Профайлаа харах эсвэл засахын тулд дээд хэсгийн бүртгэлийн хэсгээс эхлээд нэвтэрнэ үү.',
    },
    footer: {
      tagline:
        'Ховор өвчтэй монгол иргэдэд мэдээлэл, сэтгэлзүйн дэмжлэг, санхүүгийн тусламжийн замуудыг ойртуулах платформ.',
      quickLinks: 'Түргэн холбоос',
      legal: 'Эрх зүй',
      support: 'Дэмжлэг',
      privacy: 'Нууцлалын бодлого',
      disclaimer: 'Тайлбар, анхааруулга',
      accessibility: 'Хүртээмжийн мэдэгдэл',
    },
    home: {
      heroTitle: 'Ховор өвчтэй иргэдэд ойр, тайван, найдвартай дэмжлэг.',
      heroBody:
        'Rare Care нь Монгол дахь ховор өвчтэй хүмүүс, асран хамгаалагчид, гэр бүлүүдэд зориулсан мэдээлэл, өдөр тутмын урам, арга хэмжээ, санхүүгийн дэмжлэгийн гарцыг нэг дор төвлөрүүлнэ.',
      heroAside:
        'Найдвартай мэдээлэл, олон нийтийн халамж, санхүүгийн тусламжийн замыг нэг цэгт цэгцэлнэ.',
      aboutTitle: 'Бидний тухай',
      aboutBody:
        'Rare Care нь нууцлалыг хүндэтгэж, ойлгомжтой эмнэлзүйн мэдээллийг хүний халуун уур амьсгалтайгаар хүргэхийг зорьдог. Бид гэр бүл, сайн дурынхан, эмч мэргэжилтнүүдийн хамтын ажиллагааг дэмжинэ.',
      helpTitle: 'Rare Care танд хэрхэн туслах вэ?',
      helpCards: [
        {
          title: 'Найдвартай өвчний мэдээлэл олох',
          body: 'Ойлгомжтой тайлбар, эмнэлзүйн товч мэдээлэл, шинж тэмдгийн бүтэцтэй жагсаалт.',
        },
        {
          title: 'Хүмүүстэй холбогдох',
          body: 'Аюулгүй, ирээдүйд өргөжих олон нийтийн дэмжлэгийн орон зай.',
        },
        {
          title: 'Санхүүгийн тусламж хүсэх',
          body: 'Хандив, дэмжлэг, дараагийн алхамын мэдээллийг төвлөрүүлсэн урсгал.',
        },
        {
          title: 'Өдөр тутмын зөвлөгөө унших',
          body: 'Сэтгэл зүйн дэмжлэг, богинохон амьсгаа авах орон зай, урам өгөх агуулга.',
        },
      ],
      donationQuote: '“Бид олсон зүйлээрээ амьдардаг, харин өгсөн зүйлээрээ амьдралыг бүтээдэг.”',
    },
    diseases: {
      listingTitle: 'Өвчний мэдээллийн сан',
      listingBody: 'Өвчний нэр, өөр нэр, ангиллаар шүүж хайгаад илүү дэлгэрэнгүй тайлбарт орно уу.',
      searchLabel: 'Өвчний нэр эсвэл өөр нэр',
      categoryLabel: 'Ангилал',
      sortLabel: 'Эрэмбэлэх',
      sortName: 'Цагаан толгой',
      sortUpdated: 'Шинэчлэгдсэн огноо',
      aliases: 'Өөр нэрс',
      causes: 'Шалтгаан',
      symptoms: 'Шинж тэмдэг',
      medicalSummary: 'Эмнэлзүйн тайлбар',
      simpleSummary: 'Энгийн тайлбар',
      symptomMedicalTerm: 'Нэр томьёо',
      symptomDescription: 'Тайлбар',
      symptomSynonyms: 'Ижил утгатай',
      symptomFrequency: 'Давтамж',
      symptomSystem: 'Биеийн систем',
      updated: 'Шинэчилсэн',
      relatedSupport: 'Энэ мэдээлэл танд эхний алхмаа төлөвлөхөд тусална.',
    },
    dailyCorner: {
      title: 'Өдрийн булан',
      body: 'Багахан амсхийлт, сэтгэлзүйн дэмжлэг, өдөр тутмын зөөлөн сануулгыг эндээс аваарай.',
    },
    donation: {
      title: 'Хандив',
      intro:
        'Таны хандив нь Rare Care-ийн мэдээлэл түгээх, гэр бүлүүдийг холбох, тусламжийн замуудыг илүү ойртуулах ажилд зарцуулагдана.',
      donationType: 'Хандивын төрөл',
      oneTime: 'Нэг удаа',
      monthly: 'Сар бүр',
      amount: 'Хандивын дүн',
      dedicateTo: 'Энэ хандивыг зориулах хүн',
      note: 'Бидэнд үлдээх зурвас',
      yourInfo: 'Таны мэдээлэл',
      firstName: 'Нэр',
      lastName: 'Овог',
      address: 'Хаяг',
      country: 'Улс',
      stateProvince: 'Аймаг / Муж',
      city: 'Хот',
      postalCode: 'Шуудангийн код',
      email: 'Имэйл',
      phone: 'Утас',
      payment: 'Төлбөр',
      totalAmount: 'Нийт дүн',
      paymentType: 'Төлбөрийн төрөл',
      creditCard: 'Карт',
      qpay: 'QPay',
      consent: 'Миний хувийн мэдээллийг хандивын зорилгоор ашиглахыг зөвшөөрч байна.',
      captcha: 'Би робот биш',
      successTitle: 'Хандивын хүсэлт амжилттай хадгалагдлаа',
      successBody:
        'Хөгжүүлэлтийн орчинд төлбөрийг амжилттай гэж үзлээ. Бодит төлбөрийн холболтыг дараа нь сольж болно.',
    },
    events: {
      title: 'Арга хэмжээ',
      body: 'Удахгүй болох уулзалт, вебинар, хандивын өдөрлөгүүдийг эндээс үзнэ үү.',
      organizer: 'Зохион байгуулагч',
      location: 'Байршил',
      register: 'Оролцох',
      registrationIntro: 'Оролцох хүсэлтээ үлдээгээд баталгаажуулах мэдээллээ имэйлээр авна уу.',
      name: 'Нэр',
      email: 'Имэйл',
      phone: 'Утас',
      attendees: 'Оролцогчдын тоо',
      note: 'Тэмдэглэл',
      success: 'Таны бүртгэл хадгалагдлаа. Бид баталгаажуулах мэдээллийг боломжтой үед илгээнэ.',
    },
    community: {
      title: 'Олон нийт',
      body: 'MVP хувилбарт олон нийтийн орон зайг энгийн байлган, аюулгүй байдал, нууцлал, цаашдын өсөлтийн чиглэлийг тайлбарлаж байна.',
      welcome: 'Тавтай морил',
      safety: 'Аюулгүй байдал ба нууцлал',
      future: 'Цаашид хөгжих боломж',
    },
    contact: {
      title: 'Холбоо барих',
      body: 'Асуулт, хамтын ажиллагааны санал, эсвэл санал хүсэлтээ бидэнд илгээнэ үү.',
      organization: 'Rare Care Mongolia',
      name: 'Нэр',
      email: 'Имэйл',
      subject: 'Гарчиг',
      message: 'Зурвас',
      success: 'Таны зурвас хадгалагдлаа. Бид боломжит хугацаанд эргэн холбогдоно.',
    },
    legal: {
      privacyTitle: 'Нууцлалын бодлого',
      disclaimerTitle: 'Эмнэлзүйн тайлбар, анхааруулга',
      accessibilityTitle: 'Хүртээмжийн мэдэгдэл',
    },
  },
  en: {
    siteName: 'Rare Care',
    languageLabel: 'EN',
    alternateLanguageLabel: 'MN',
    nav: {
      accessibility: 'Accessibility',
      events: 'Events',
      dailyCorner: 'Daily Corner',
      contact: 'Contact Us',
      diseaseInformation: 'Disease Information',
      community: 'Community',
      donate: 'Donate',
      searchPlaceholder: 'Search diseases...',
    },
    common: {
      home: 'Home',
      siteRegion: 'Mongolia',
      learnMore: 'Learn More',
      readNow: 'Read Now',
      joinGroup: 'Join Group',
      applyNow: 'Apply Now',
      makeDonation: 'Make Donation',
      upcomingEvents: 'Upcoming Events',
      everydayTips: 'Everyday Tips',
      educationalDisclaimer:
        'This information is educational and does not replace professional medical advice.',
      noResults: 'No matching information was found.',
      audio: 'Audio option',
      submit: 'Submit',
      sending: 'Sending...',
      search: 'Search',
      reset: 'Reset',
      other: 'Other',
      openMenu: 'Open menu',
      closeMenu: 'Close menu',
      submitError: 'There was a problem submitting the form.',
      generalError: 'Something went wrong',
      postedOn: 'Date',
      allCategories: 'All categories',
      notFound: 'Page or information not found.',
    },
    auth: {
      account: 'Account',
      login: 'Login',
      register: 'Register',
      profile: 'Profile',
      logout: 'Logout',
      signedInAs: 'Signed in as',
      welcomeTitle: 'Welcome to Rare Care',
      welcomeBody: 'Sign in to keep your place and connect with future support features in a calmer, more personal way.',
      loginTitle: 'Login',
      loginBody: 'Use your email and password to sign in securely.',
      registerTitle: 'Create Account',
      registerBody: 'Set up a simple account to stay connected as Rare Care grows.',
      name: 'Name',
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      createAccount: 'Create Account',
      close: 'Close',
      passwordHint: 'Use at least 8 characters.',
      emailRequired: 'Enter your email address.',
      emailInvalid: 'Enter a valid email address.',
      nameRequired: 'Enter your name.',
      nameMinLength: 'Name must be at least 2 characters.',
      passwordRequired: 'Enter your password.',
      passwordMinLength: 'Password must be at least 8 characters.',
      confirmPasswordRequired: 'Confirm your password.',
      passwordMismatch: 'Passwords do not match.',
      loginCta: 'Login Now',
      registerCta: 'New Account',
    },
    profile: {
      title: 'Profile',
      body: 'Review your name, picture, and account details in one calm place.',
      photoUpload: 'Upload profile photo',
      photoHelp: 'Choose an image file. Common JPG and PNG files work well.',
      photoPreview: 'Photo preview',
      removePhoto: 'Remove photo',
      photoTypeError: 'Please choose an image file.',
      photoSizeError: 'That image is too large. Please choose a file under 4MB.',
      emailReadonly: 'Your email is currently view-only.',
      memberSince: 'Member since',
      save: 'Save Profile',
      success: 'Your profile was updated successfully.',
      signedOutTitle: 'Sign in to view your profile',
      signedOutBody:
        'Use the account area in the header first, then return here to manage your details.',
    },
    footer: {
      tagline:
        'A calm, trustworthy platform connecting people in Mongolia with rare disease information, emotional support, and financial assistance pathways.',
      quickLinks: 'Quick Links',
      legal: 'Legal',
      support: 'Support',
      privacy: 'Privacy Policy',
      disclaimer: 'Disclaimer',
      accessibility: 'Accessibility Statement',
    },
    home: {
      heroTitle: 'Warm, practical support for people living with rare disease.',
      heroBody:
        'Rare Care brings together reliable disease information, everyday emotional support, events, and donation pathways for Mongolian patients, caregivers, and families.',
      heroAside:
        'Reliable information, community care, and financial support pathways in one place.',
      aboutTitle: 'About Us',
      aboutBody:
        'Rare Care is designed to protect privacy, explain medical topics in clearer language, and support collaboration across families, volunteers, and clinicians.',
      helpTitle: 'How Can Rare Care Help You?',
      helpCards: [
        {
          title: 'Find Reliable Disease Information',
          body: 'Browse clear summaries, medical context, and symptom structures in one organized library.',
        },
        {
          title: 'Connect With People',
          body: 'Start with a simple, privacy-aware community area designed to expand safely later.',
        },
        {
          title: 'Apply for Financial Assistance',
          body: 'Use donation and support pathways designed to become more actionable over time.',
        },
        {
          title: 'Discover Helpful Everyday Tips',
          body: 'Read reflective guidance and emotional support content that feels calm rather than clinical.',
        },
      ],
      donationQuote: '"We make a living by what we get, but we make a life by what we give."',
    },
    diseases: {
      listingTitle: 'Disease Information Library',
      listingBody:
        'Search by disease name, alternative names, or category to find the right page quickly.',
      searchLabel: 'Disease name or alias',
      categoryLabel: 'Category',
      sortLabel: 'Sort',
      sortName: 'Alphabetical',
      sortUpdated: 'Recently updated',
      aliases: 'Alternative names',
      causes: 'Causes',
      symptoms: 'Symptoms',
      medicalSummary: 'Medical summary',
      simpleSummary: 'Simple explanation',
      symptomMedicalTerm: 'Medical term',
      symptomDescription: 'Description',
      symptomSynonyms: 'Synonyms',
      symptomFrequency: 'Frequency',
      symptomSystem: 'Body system',
      updated: 'Updated',
      relatedSupport: 'Use this page to prepare questions and plan your next care step.',
    },
    dailyCorner: {
      title: 'Daily Corner',
      body: 'A quieter page for emotional support, reflection, and gentle daily reminders.',
    },
    donation: {
      title: 'Donate',
      intro:
        'Your donation helps Rare Care continue building trustworthy information, stronger support pathways, and everyday care resources for people with rare diseases in Mongolia.',
      donationType: 'Donation Type',
      oneTime: 'One-Time',
      monthly: 'Monthly',
      amount: 'Donation Amount',
      dedicateTo: 'Dedicate This Donation',
      note: 'Write Note To Us',
      yourInfo: 'Your Information',
      firstName: 'First Name',
      lastName: 'Last Name',
      address: 'Address',
      country: 'Country',
      stateProvince: 'State / Province',
      city: 'City',
      postalCode: 'Postal Code',
      email: 'Email',
      phone: 'Phone Number',
      payment: 'Payment',
      totalAmount: 'Total Donation Amount',
      paymentType: 'Payment Type',
      creditCard: 'Credit Card',
      qpay: 'QPay',
      consent:
        'I agree to the collection of my personal information for the donor section described in the Privacy Policy.',
      captcha: "I'm not a robot",
      successTitle: 'Donation saved successfully',
      successBody:
        'In development, the payment was marked successful. The payment layer is abstracted so a real gateway can be added later.',
    },
    events: {
      title: 'Events',
      body: 'Browse upcoming gatherings, webinars, and fundraising opportunities.',
      organizer: 'Organizer',
      location: 'Location',
      register: 'Register',
      registrationIntro:
        'Leave your details and we will follow up with confirmation information by email.',
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      attendees: 'Number of attendees',
      note: 'Note',
      success:
        'Your registration was saved. We will follow up with confirmation details when available.',
    },
    community: {
      title: 'Community',
      body: 'The MVP keeps community simple while setting expectations around privacy, safety, and future moderated support spaces.',
      welcome: 'Welcome',
      safety: 'Safety and privacy',
      future: 'What comes next',
    },
    contact: {
      title: 'Contact Us',
      body: 'Send questions, collaboration ideas, or feedback and we will follow up when possible.',
      organization: 'Rare Care Mongolia',
      name: 'Name',
      email: 'Email',
      subject: 'Subject',
      message: 'Message',
      success: 'Your message was saved. We will follow up as soon as we can.',
    },
    legal: {
      privacyTitle: 'Privacy Policy',
      disclaimerTitle: 'Medical Disclaimer',
      accessibilityTitle: 'Accessibility Statement',
    },
  },
};

export function normalizeLocale(value: string | null | undefined): Locale {
  return value === 'en' ? 'en' : 'mn';
}

export function dictionaryFor(locale: Locale): Dictionary {
  return dictionaries[locale];
}

export function formatDisplayDate(value: string, locale: Locale): string {
  return new Intl.DateTimeFormat(locale === 'mn' ? 'mn-MN' : 'en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  }).format(new Date(value));
}

export function formatMonthDay(value: string, locale: Locale): string {
  return new Intl.DateTimeFormat(locale === 'mn' ? 'mn-MN' : 'en-US', {
    month: 'short',
    day: 'numeric',
  }).format(new Date(value));
}
