import { Locale } from './models';

export type Dictionary = typeof dictionaries.mn;

export const dictionaries = {
  mn: {
    siteName: 'Ховорхон',
    languageLabel: 'MN',
    alternateLanguageLabel: 'EN',
    nav: {
      accessibility: 'Хүртээмж',
      events: 'Арга хэмжээ',
      dailyCorner: 'Өдрийн булан',
      contact: 'Холбоо барих',
      diseaseInformation: 'Өвчний мэдээлэл',
      community: 'Олон нийт',
      donate: 'Хандив',
      searchPlaceholder: 'Өвчнөөр хайх...',
    },
    common: {
      home: 'Нүүр',
      siteRegion: 'Монгол',
      learnMore: 'Дэлгэрэнгүй',
      readNow: 'Унших',
      joinGroup: 'Нэгдэх',
      applyNow: 'Хүсэлт илгээх',
      makeDonation: 'Хандив өргөх',
      upcomingEvents: 'Удахгүй болох арга хэмжээ',
      everydayTips: 'Өдөр тутмын зөвлөгөө',
      educationalDisclaimer:
        'Энэ хэсгийн мэдээлэл нь боловсролын зориулалттай бөгөөд эмчийн мэргэжлийн зөвлөгөөг орлохгүй.',
      noResults: 'Тохирох мэдээлэл олдсонгүй.',
      audio: 'Аудио хувилбар',
      submit: 'Илгээх',
      sending: 'Илгээж байна...',
      search: 'Хайх',
      reset: 'Арилгах',
      other: 'Бусад',
      openMenu: 'Цэс нээх',
      closeMenu: 'Цэс хаах',
      submitError: 'Илгээх үед алдаа гарлаа.',
      generalError: 'Алдаа гарлаа',
      postedOn: 'Огноо',
      allCategories: 'Бүх ангилал',
      notFound: 'Хуудас эсвэл мэдээлэл олдсонгүй.',
    },
    auth: {
      account: 'Бүртгэл',
      login: 'Нэвтрэх',
      register: 'Бүртгүүлэх',
      profile: 'Профайл',
      userManagement: 'Хэрэглэгч удирдах',
      contentManagement: 'Контент удирдах',
      eventManagement: 'Арга хэмжээ удирдах',
      dailyCornerManagement: 'Өдрийн булан удирдах',
      diseaseManagement: 'Өвчний мэдээлэл удирдах',
      logout: 'Гарах',
      signedInAs: 'Нэвтэрсэн хэрэглэгч',
      welcomeTitle: 'Rare Care-д тавтай морил',
      welcomeBody: 'Өөрийн бүртгэлээр нэвтэрч хадгалсан оролцоо, цаашдын дэмжлэгийн боломжууддаа холбогдоорой.',
      loginTitle: 'Нэвтрэх',
      loginBody: 'Хэрэглэгчийн нэр эсвэл имэйл, нууц үгээрээ аюулгүй нэвтэрнэ үү.',
      registerTitle: 'Бүртгэл үүсгэх',
      registerBody: 'Энгийн бүртгэл үүсгээд Rare Care-ийн ирээдүйн дэмжлэгийн боломжуудтай холбогдоорой.',
      username: 'Хэрэглэгчийн нэр',
      loginIdentifier: 'Хэрэглэгчийн нэр эсвэл имэйл',
      loginIdentifierRequired: 'Хэрэглэгчийн нэр эсвэл имэйлээ оруулна уу.',
      name: 'Нэр',
      email: 'Имэйл',
      password: 'Нууц үг',
      confirmPassword: 'Нууц үгээ давтана уу',
      createAccount: 'Бүртгэл үүсгэх',
      close: 'Хаах',
      passwordHint: 'Нууц үг хамгийн багадаа 8 тэмдэгт байна.',
      emailRequired: 'Имэйлээ оруулна уу.',
      emailInvalid: 'Зөв имэйл хаяг оруулна уу.',
      nameRequired: 'Нэрээ оруулна уу.',
      nameMinLength: 'Нэр хамгийн багадаа 2 тэмдэгт байна.',
      passwordRequired: 'Нууц үгээ оруулна уу.',
      passwordMinLength: 'Нууц үг хамгийн багадаа 8 тэмдэгт байна.',
      confirmPasswordRequired: 'Нууц үгээ дахин оруулна уу.',
      passwordMismatch: 'Нууц үгүүд таарахгүй байна.',
      loginCta: 'Одоо нэвтрэх',
      registerCta: 'Шинэ бүртгэл',
    },
    profile: {
      title: 'Профайл',
      body: 'Өөрийн нэр, зураг, бүртгэлийн мэдээллээ энэ хэсгээс хянаарай.',
      photoUpload: 'Профайл зураг оруулах',
      photoHelp: 'Зурагтай файл сонгоно уу. JPG, PNG зэрэг ердийн зураг ажиллана.',
      photoPreview: 'Зургийн харагдац',
      removePhoto: 'Зураг арилгах',
      photoTypeError: 'Зөвхөн зураг файл оруулна уу.',
      photoSizeError: 'Зургийн хэмжээ хэт том байна. 4MB-аас бага файл сонгоно уу.',
      usernameReadonly: 'Хэрэглэгчийн нэрийг одоогоор зөвхөн харах боломжтой.',
      emailReadonly: 'Имэйл хаягийг одоогоор зөвхөн харах боломжтой.',
      memberSince: 'Элссэн огноо',
      save: 'Профайл хадгалах',
      success: 'Профайл амжилттай шинэчлэгдлээ.',
      signedOutTitle: 'Профайлд нэвтрэх шаардлагатай',
      signedOutBody:
        'Профайлаа харах эсвэл засахын тулд дээд хэсгийн бүртгэлийн хэсгээс эхлээд нэвтэрнэ үү.',
    },
    footer: {
      tagline:
        'Ховор өвчтэй монгол иргэдэд мэдээлэл, сэтгэлзүйн дэмжлэг, санхүүгийн тусламжийн замуудыг ойртуулах платформ.',
      quickLinks: 'Түргэн холбоос',
      legal: 'Эрх зүй',
      support: 'Дэмжлэг',
      privacy: 'Нууцлалын бодлого',
      disclaimer: 'Тайлбар, анхааруулга',
      accessibility: 'Хүртээмжийн мэдэгдэл',
    },
    home: {
      heroTitle: 'Ховор өвчтэй иргэдэд ойр, тайван, найдвартай дэмжлэг.',
      heroBody:
        'Rare Care нь Монгол дахь ховор өвчтэй хүмүүс, асран хамгаалагчид, гэр бүлүүдэд зориулсан мэдээлэл, өдөр тутмын урам, арга хэмжээ, санхүүгийн дэмжлэгийн гарцыг нэг дор төвлөрүүлнэ.',
      heroAside:
        'Найдвартай мэдээлэл, олон нийтийн халамж, санхүүгийн тусламжийн замыг нэг цэгт цэгцэлнэ.',
      aboutTitle: 'Бидний тухай',
      aboutBody:
        'Rare Care нь нууцлалыг хүндэтгэж, ойлгомжтой эмнэлзүйн мэдээллийг хүний халуун уур амьсгалтайгаар хүргэхийг зорьдог. Бид гэр бүл, сайн дурынхан, эмч мэргэжилтнүүдийн хамтын ажиллагааг дэмжинэ.',
      helpTitle: 'Rare Care танд хэрхэн туслах вэ?',
      helpCards: [
        {
          title: 'Найдвартай өвчний мэдээлэл олох',
          body: 'Ойлгомжтой тайлбар, эмнэлзүйн товч мэдээлэл, шинж тэмдгийн бүтэцтэй жагсаалт.',
        },
        {
          title: 'Хүмүүстэй холбогдох',
          body: 'Аюулгүй, ирээдүйд өргөжих олон нийтийн дэмжлэгийн орон зай.',
        },
        {
          title: 'Санхүүгийн тусламж хүсэх',
          body: 'Хандив, дэмжлэг, дараагийн алхамын мэдээллийг төвлөрүүлсэн урсгал.',
        },
        {
          title: 'Өдөр тутмын зөвлөгөө унших',
          body: 'Сэтгэл зүйн дэмжлэг, богинохон амьсгаа авах орон зай, урам өгөх агуулга.',
        },
      ],
      donationImpactTitle: 'Таны хандив хэрхэн тусалдаг вэ?',
      donationImpactCards: [
        {
          icon: '♥',
          title: 'Өвчтөнд дэмжлэг',
          body: 'Эмчилгээ, эмнэлгийн хэрэгцээнд зориулсан санхүүгийн тусламжийг дэмжинэ.',
        },
        {
          icon: '📖',
          title: 'Мэдээллийн хүртээмж',
          body: 'Монгол хэл дээр найдвартай ховор өвчний мэдээлэл бэлтгэж, орчуулна.',
        },
        {
          icon: '▣',
          title: 'Платформын хөгжил',
          body: 'Ховор өвчний олон нийтэд илүү сайн үйлчлэх платформыг сайжруулна.',
        },
        {
          icon: '●',
          title: 'Арга хэмжээ ба олон нийт',
          body: 'Мэдлэг түгээх аян, уулзалт, олон нийтийн арга хэмжээг дэмжинэ.',
        },
      ],
      donationTrustTitle: 'Ил тод байдал ба итгэл',
      donationTrustBody:
        'Бид бүх хандивыг хариуцлагатай, ил тод ашиглахыг эрмэлздэг. Хандив бүр утга учиртай нөлөө авчирна.',
      donationHopeTitle: 'Хандив бүр найдвар, хүч, дэмжлэг авчирдаг.',
      donationHopeBody: 'Өөрчлөлтийн нэг хэсэг болж байгаад баярлалаа.',
      donationQuote: '“Бид олсон зүйлээрээ амьдардаг, харин өгсөн зүйлээрээ амьдралыг бүтээдэг.”',
    },
    diseases: {
      listingTitle: 'Өвчний мэдээллийн сан',
      listingBody:
        'GARD-ийн жишгээр үсэг, ангилал, өвчний нэрээр нь шүүж олон ховор өвчний лавлах мэдээлэл рүү орно уу.',
      gardReference:
        'Энэ хэсгийг NIH-ийн GARD өвчний жагсаалт болон өвчний ангиллын бүтэц дээр тулгуурлан өргөтгөв.',
      keywordLabel: 'Түлхүүр үг',
      filterLabel: 'Шүүлтүүр',
      searchLabel: 'Өвчний нэр эсвэл өөр нэр',
      searchPlaceholder: 'Өвчний нэр, товчлол эсвэл өөр нэрээр хайх',
      categoryLabel: 'Ангилал',
      browseByLetter: 'Үсгээр үзэх',
      browseByLetterBody: 'Өвчний нэрийн эхний үсгээр хурдан шүүнэ үү.',
      browseByCategory: 'Өвчний ангиллаар үзэх',
      browseByCategoryBody: 'GARD-ийн албан ёсны ангиллаар шүүж үзнэ үү.',
      showingResults: '{count} өвчин харуулж байна',
      showingRange: '{count} өвчнөөс {start} - {end}',
      gardSourceBadge: 'GARD',
      allLetters: 'Бүх үсэг',
      paginationLabel: 'Өвчний хуудсууд',
      previousPage: 'Өмнөх',
      nextPage: 'Дараах',
      sortLabel: 'Эрэмбэлэх',
      sortByPrefix: 'Эрэмбэ',
      sortName: 'Цагаан толгой',
      sortUpdated: 'Шинэчлэгдсэн огноо',
      aliases: 'Өөр нэрс',
      mainDiseaseType: 'Үндсэн өвчний төрөл',
      relatedDiseaseTypes: 'Холбогдох ангиллууд',
      relatedTypeCount: 'Өөр {count} холбогдох ангилал',
      causes: 'Шалтгаан',
      symptoms: 'Шинж тэмдэг',
      atAGlance: 'Товч харах',
      references: 'Эх сурвалж',
      sourceTitle: 'Эх сурвалжийн тайлбар',
      sourceBody:
        'Rare Care энэ бичлэгийг GARD лавлах дээр тулгуурлан индексэлсэн тул илүү дэлгэрэнгүй өвчний мэдээллийг доорх холбоосоор нээнэ үү.',
      noCauseDetails:
        'Энэ бичлэгийн шалтгааны дэлгэрэнгүй тайлбарыг Rare Care дээр одоогоор өргөтгөөгүй байна.',
      noSymptomDetails:
        'Энэ бичлэгийн шинж тэмдгийн дэлгэрэнгүй тайлбарыг Rare Care дээр одоогоор өргөтгөөгүй байна.',
      medicalSummary: 'Эмнэлзүйн тайлбар',
      simpleSummary: 'Энгийн тайлбар',
      symptomMedicalTerm: 'Нэр томьёо',
      symptomDescription: 'Тайлбар',
      symptomSynonyms: 'Ижил утгатай',
      symptomFrequency: 'Давтамж',
      symptomSystem: 'Биеийн систем',
      mainCauseTitle: 'Гол шалтгаан',
      mainCausesTitle: 'Гол шалтгаанууд',
      generalSymptomsGroup: 'Ерөнхий',
      symptomDetailsLabel: 'Дэлгэрэнгүй',
      symptomSearchLabel: 'Шинж тэмдгээр хайх',
      symptomSearchPlaceholder: 'Нэр томьёо, тайлбар эсвэл ижил утгаар хайх',
      symptomFiltersLabel: 'Биеийн системээр шүүх',
      symptomVisibleCount: '{count} шинж тэмдэг харагдаж байна',
      allSystems: 'Бүх систем',
      noFilteredSymptoms:
        'Энэ шүүлтүүрээр тохирох шинж тэмдэг олдсонгүй. Өөр систем эсвэл өөр түлхүүр үгээр хайж үзээрэй.',
      mainSymptomsTitle: 'Гол шинж тэмдгүүд',
      quickPoints: 'Гол санаанууд',
      symptomCountLabel: '{count} шинж тэмдэг багтсан',
      symptomSystemsLabel: 'Түгээмэл холбоотой системүүд',
      variableSymptomsLabel: 'Шинж тэмдэг хүн бүрт өөр байж болно',
      multipleCategoriesLabel: 'Олон эрхтэн тогтолцоог хамарч болзошгүй',
      updated: 'Шинэчилсэн',
    },
    dailyCorner: {
      title: 'Өдрийн булан',
      body:
        'Өдрийн булан нь өдөр бүр таны сэтгэл зүйн сайн сайхныг дэмжих богино атлаа утга учиртай санааг хүргэнэ. Хэрэгтэй мөч бүрд энгийн эргэцүүлэл, зоригжуулалт, тайвшрах нэгэн агшныг санал болгоно.',
      accessibilityNote:
        'Өдрийн булан нь мөн нэмэлт аудио сонголтоор хүртээмжийг дэмждэг бөгөөд ингэснээр хэрэглэгчид текст уншихын оронд сонсох боломжтой. Энэ нь ядарсан, нүд чилсэн, сэтгэлээр ачаалсан, эсвэл аудио хэлбэрээр хүлээж авахад илүү тухтай хүмүүст тусална.',
    },
    donation: {
      title: 'Хандив',
      intro:
        'Rare Care дахь хандивууд нь тусгай мэргэжлийн тусламж авахад санхүүгийн хүндрэлтэй тулгарч буй ховор өвчтэй хүмүүст дэмжлэг үзүүлэхэд ашиглагдана. Энэхүү хувь нэмэр нь найдвартай мэдээллийн хүртээмжийг сайжруулах, олон нийтийн дэмжлэгийг бэхжүүлэх, мөн Монгол даяарх өвчтөнүүдийг холбож, чадавхжуулах платформыг тогтвортой авч явахад тусалдаг.',
      donationType: 'Хандивын төрөл',
      oneTime: 'Нэг удаа',
      monthly: 'Сар бүр',
      amount: 'Хандивын дүн',
      dedicateTo: 'Энэ хандивыг зориулах хүн',
      note: 'Бидэнд үлдээх зурвас',
      yourInfo: 'Таны мэдээлэл',
      firstName: 'Нэр',
      lastName: 'Овог',
      address: 'Хаяг',
      country: 'Улс',
      stateProvince: 'Аймаг / Муж',
      city: 'Хот',
      postalCode: 'Шуудангийн код',
      email: 'Имэйл',
      phone: 'Утас',
      payment: 'Төлбөр',
      totalAmount: 'Нийт дүн',
      paymentType: 'Төлбөрийн төрөл',
      creditCard: 'Карт',
      qpay: 'QPay',
      consent: 'Миний хувийн мэдээллийг хандивын зорилгоор ашиглахыг зөвшөөрч байна.',
      captcha: 'Би робот биш',
      successTitle: 'Хандивын хүсэлт амжилттай хадгалагдлаа',
      successBody:
        'Хөгжүүлэлтийн орчинд төлбөрийг амжилттай гэж үзлээ. Бодит төлбөрийн холболтыг дараа нь сольж болно.',
    },
    events: {
      title: 'Арга хэмжээ',
      body: 'Удахгүй болох уулзалт, вебинар, хандивын өдөрлөгүүдийг эндээс үзнэ үү.',
      organizer: 'Зохион байгуулагч',
      location: 'Байршил',
      register: 'Оролцох',
      posterBrand: 'Rare Care Mongolia',
      posterForum: 'Гэр бүл, хамтын дэмжлэг',
      posterWebinar: 'Шууд онлайн уулзалт',
      posterFundraiser: 'Хамтын дэмжлэгийн аян',
      posterDate: 'Огноо',
      posterTime: 'Цаг',
      posterPlace: 'Хаана',
      registrationIntro: 'Оролцох хүсэлтээ үлдээгээд баталгаажуулах мэдээллээ имэйлээр авна уу.',
      name: 'Нэр',
      email: 'Имэйл',
      phone: 'Утас',
      attendees: 'Оролцогчдын тоо',
      note: 'Тэмдэглэл',
      success: 'Таны бүртгэл хадгалагдлаа. Бид баталгаажуулах мэдээллийг боломжтой үед илгээнэ.',
    },
    community: {
      title: 'Олон нийт',
      body:
        'Ховор өвчний туршлагаа хуваалцдаг хүмүүсийг аюулгүй, дэмжлэгтэй орчинд холбож, асуулт асуух, туршлага солилцох, ганцаардлыг багасгах орон зай.',
      coreIdea: 'Холбоо, дэмжлэг, хамтын ойлголцол аюулгүй орчинд.',
      primaryAction: 'Асуулт асуух',
      secondaryAction: 'Дэмжлэгийн бүлэг үзэх',
      supportTitle: 'Өөрт хэрэгтэй дэмжлэгээ хурдан олоорой',
      supportItems: [
        {
          icon: '♡',
          title: 'Ижил туршлагатай хүмүүстэй холбогдох',
          body: 'Өвчтөн, асран хамгаалагч, гэр бүлийн гишүүд өөртэй тань төстэй зам туулж буй хүмүүсийг олоход тусална.',
        },
        {
          icon: '?',
          title: 'Чиглүүлэгтэй форум',
          body: 'Өвчин, сэдэв, хэрэгцээгээр нь ангилсан асуулт, хэлэлцүүлэг нь мэдээллийг илүү эмх цэгцтэй болгоно.',
        },
        {
          icon: '✦',
          title: 'Мэдлэг ба туршлага хуваалцах',
          body: 'Бодит амьдралын зөвлөгөө, асаргаа, оношилгоо, өдөр тутмын зохицуулалтын туршлагыг хуваалцана.',
        },
        {
          icon: '●',
          title: 'Ганцаардал ба гутаан доромжлолыг бууруулах',
          body: 'Хүн бүр сонсогдож, ойлгогдож, хамт олон дунд багтаж байгаагаа мэдрэхэд чиглэнэ.',
        },
      ],
      forumTitle: 'Чиглүүлэгтэй Q&A форум',
      forumBody:
        'Асуултаа өвчин, сэдэв, хэрэгцээгээр ангилж хайснаар зөв хүмүүс, зөв мэдээлэлд илүү хурдан хүрнэ.',
      searchPlaceholder: 'Асуулт, өвчин, эсвэл сэдвээр хайх...',
      allDiseases: 'Бүх өвчин',
      allTopics: 'Бүх сэдэв',
      groupTitle: 'Дэмжлэгийн бүлгүүд',
      groupBody: 'Үүрэг, хэрэгцээ, нөхцөл байдлаар бүлгүүдэд нэгдэж дэмжлэг авах боломжтой.',
      groups: [
        {
          role: 'Өвчтөн',
          title: 'Rare Warriors өвчтөний хүрээлэл',
          body: 'Ховор өвчинтэй амьдарч буй хүмүүс түүх, эх сурвалж, урам зориг хуваалцах орон зай.',
          members: '14 гишүүн',
        },
        {
          role: 'Асран хамгаалагч',
          title: 'Caregiver Hearts сүлжээ',
          body: 'Асран хамгаалагчид практик зөвлөгөө, сэтгэлзүйн дэмжлэг, өөрийгөө хамгаалах аргаа солилцоно.',
          members: '14 гишүүн',
        },
        {
          role: 'Гэр бүл',
          title: 'Family Bonds дэмжлэгийн төв',
          body: 'Гэр бүлийн гишүүд ойлголт, зөвлөгөө, ижил нөхцөлтэй хүмүүстэй холбоо олно.',
          members: '14 гишүүн',
        },
      ],
      storyTitle: 'Хуваалцсан туршлагууд',
      storyBody: 'Бодит дуу хоолой, бодит зориг. Өөрийн түүхээ нэрээ нууцлан эсвэл нэртэйгээр хуваалцаарай.',
      shareExperience: 'Туршлагаа хуваалцах',
      shareExperienceTitle: 'Туршлагаа хуваалцах',
      shareExperienceIntro:
        'Таны түүх бусдад тайвшрал, зориг, ганцаараа биш гэсэн мэдрэмж өгч чадна. Өөрт тухтай хэмжээндээ хуваалцаарай.',
      storyNameLabel: 'Нэр',
      storyNamePlaceholder: 'Жишээ: Золбаяр Энх',
      storyRoleLabel: 'Та хэн бэ?',
      storyRolePatient: 'Өвчтөн',
      storyRoleCaregiver: 'Асран хамгаалагч',
      storyRoleFamily: 'Гэр бүлийн гишүүн',
      storyRoleSupporter: 'Дэмжигч',
      storyDiseaseLabel: 'Өвчин эсвэл нөхцөл байдал (заавал биш)',
      storyDiseasePlaceholder: 'Жишээ: оношилгооны аялал, өдөр тутмын асаргаа',
      storyMessageLabel: 'Таны түүх',
      storyMessagePlaceholder:
        'Юу тохиолдсон, юу тус болсон, бусдад ямар найдвар эсвэл зөвлөгөө өгөхийг хүсэж байгаагаа бичээрэй...',
      storyGuideTitle: 'Оруулж болох гол зүйлс',
      storyGuideItems: [
        'Таны аяллын нэг чухал мөч',
        'Танд тус болсон дэмжлэг, мэдээлэл, дадал',
        'Ижил зам туулж буй хүмүүст хэлэх урам',
        'Хуваалцахад тухгүй хувийн мэдээллээ орхих боломжтой',
      ],
      storyAnonymousLabel: 'Нэрээ нууцлан нийтлэх',
      storyConsentLabel:
        'Энэ түүх олон нийтэд харагдах боломжтойг ойлгож байна. Би өөрийн болон бусдын нууц, эмзэг мэдээллийг оруулахгүй.',
      storyCancel: 'Цуцлах',
      storySubmit: 'Түүхээ хуваалцах',
      storyRequired: 'Түүхээ хамгийн багадаа 40 тэмдэгтээр бичиж, шаардлагатай зөвшөөрлийг тэмдэглэнэ үү.',
      storySuccess: 'Таны түүх Shared Experiences хэсэгт нэмэгдлээ.',
      storyAnonymousName: 'Нэрээ нууцалсан гишүүн',
      stories: [
        {
          name: 'Золбаяр Энх',
          role: 'Өвчтөн',
          body:
            'Онош сонссон эхний үед би бүрэн ганцаараа мэт санагдсан. Ижил зам туулж буй хүмүүс байгааг мэдэх нь үргэлжлүүлэх хүч өгдөг.',
        },
        {
          name: 'Наранцэцэг Болд',
          role: 'Асран хамгаалагч',
          body:
            'Зарим өдөр маш их ачаалалтай байдаг ч бусадтай холбогдох нь энэ аялалд ганцаараа биш гэдгийг сануулдаг.',
        },
      ],
      promiseTitle: 'Аюулгүй орчны амлалт',
      promiseItems: [
        'Хүндэтгэлтэй, шүүмжлэлгүй харилцаа',
        'Хувийн мэдээллийг хамгаалах зарчим',
        'Модератортой, чиглүүлэгтэй хэлэлцүүлэг',
        'Эмчийн зөвлөгөөг орлохгүй, харин дэмжлэг нэмэх орон зай',
      ],
    },
    contact: {
      title: 'Холбоо барих',
      body: 'Асуулт, хамтын ажиллагааны санал, эсвэл санал хүсэлтээ бидэнд илгээнэ үү.',
      organization: 'Rare Care Mongolia',
      name: 'Нэр',
      email: 'Имэйл',
      subject: 'Гарчиг',
      message: 'Зурвас',
      success: 'Таны зурвас хадгалагдлаа. Бид боломжит хугацаанд эргэн холбогдоно.',
    },
    admin: {
      title: 'Хэрэглэгчийн удирдлага',
      body: 'Админ хэрэглэгчид бүртгэлүүдийг үүсгэж, бусад хэрэглэгчдэд админ эрх өгөх боломжтой.',
      createTitle: 'Шинэ хэрэглэгч үүсгэх',
      createButton: 'Хэрэглэгч нэмэх',
      listTitle: 'Одоогийн хэрэглэгчид',
      listBody: 'Хэрэглэгчдийн бүртгэлийг хянаж, админ удирдах талбаруудыг эндээс шинэчилнэ.',
      detailTitle: 'Хэрэглэгчийн дэлгэрэнгүй',
      updateTitle: 'Админы удирдах мэдээлэл',
      accessDeniedTitle: 'Админ эрх шаардлагатай',
      accessDeniedBody: 'Энэ хэсэгт зөвхөн админ хэрэглэгч хандах боломжтой.',
      createHelp: 'Шинэ хэрэглэгчдэд хэрэглэгчийн нэр, имэйл, нууц үг онооно.',
      detailHelp: 'Эндээс зөвхөн бүртгэлийн удирдлагатай холбоотой мэдээллийг өөрчилнө.',
      roleAdmin: 'Админ',
      roleUser: 'Хэрэглэгч',
      makeAdmin: 'Админ болгох',
      created: 'Шинэ хэрэглэгч амжилттай үүслээ.',
      promoted: 'Хэрэглэгч админ эрхтэй боллоо.',
      updated: 'Хэрэглэгчийн удирдах мэдээлэл шинэчлэгдлээ.',
      noUsers: 'Харуулах хэрэглэгч алга байна.',
      resetPassword: 'Шинэ нууц үг',
      resetPasswordHelp: 'Хоосон үлдээвэл одоогийн нууц үг өөрчлөгдөхгүй.',
      personalInfo: 'Хувийн мэдээлэл',
      accountInfo: 'Бүртгэлийн мэдээлэл',
      openDetail: 'Дэлгэрэнгүй харах',
      role: 'Эрх',
      contentStudioTitle: 'Контент бүртгэх хэсэг',
      contentStudioBody:
        'Сайтын гол агуулгуудыг бүтэцтэйгээр үүсгэж, нийтлэх хэл, төлөв, үндсэн мэдээллийг нэг дор бөглөнө үү.',
      createEventTitle: 'Арга хэмжээ бүртгэх',
      createEventButton: 'Арга хэмжээ нэмэх',
      createEventHelp:
        'Гарчиг, огноо, зохион байгуулагч, товч тайлбар зэрэг мэдээллийг бүртгээд нийтэлнэ үү.',
      createDailyTitle: 'Өдрийн булан бүртгэх',
      createDailyButton: 'Өдрийн булан нэмэх',
      createDailyHelp:
        'Өдөр тутмын урам, зөөлөн сануулга, аудио холбоос зэрэг мэдээллээ эндээс бэлтгэнэ.',
      createDiseaseTitle: 'Өвчний мэдээлэл бүртгэх',
      createDiseaseButton: 'Өвчний мэдээлэл нэмэх',
      createDiseaseHelp:
        'Өвчний үндсэн тайлбар, шалтгаан, шинж тэмдэг, эх сурвалжийг бүтэцтэйгээр хадгална.',
      eventCardBody: 'Арга хэмжээний товч агуулга, огноо, байршил, бүртгэлийн холбоосыг бэлтгэнэ.',
      dailyCardBody: 'Өдрийн буланд зориулсан гарчиг, эшлэл, сануулга, дууны холбоосыг нийтэлнэ.',
      diseaseCardBody:
        'Өвчний тайлбар, шалтгаан, шинж тэмдэг, эх сурвалжийг олон хэсгээр бүртгэнэ.',
      basicsSection: 'Үндсэн мэдээлэл',
      publishingSection: 'Нийтлэх тохиргоо',
      detailsSection: 'Нэмэлт мэдээлэл',
      causesSection: 'Шалтгаанууд',
      symptomsSection: 'Шинж тэмдгүүд',
      referencesSection: 'Эх сурвалжууд',
      localeLabel: 'Хэл',
      publishLabel: 'Нэн даруй нийтлэх',
      summaryLabel: 'Товч тайлбар',
      descriptionLabel: 'Дэлгэрэнгүй тайлбар',
      dateLabel: 'Огноо',
      startTimeLabel: 'Эхлэх цаг',
      endTimeLabel: 'Дуусах цаг',
      visualToneLabel: 'Зургийн өнгө аяc',
      visualToneHelp:
        'Сонгосон өнгө нь карт дээрх хийсвэр дүрслэлийн өнгө төрхийг өөрчилнө.',
      eventLinkLabel: 'Холбоос',
      quoteLabel: 'Эшлэл',
      reminderTitleLabel: 'Сануулах гарчиг',
      reminderBodyLabel: 'Сануулах тайлбар',
      audioUrlLabel: 'Аудио холбоос',
      slugLabel: 'Slug',
      slugHelp: 'Хоосон үлдээвэл өвчний нэрээс автоматаар үүснэ.',
      aliasesLabel: 'Өөр нэрс',
      aliasesHelp: 'Олон утгыг таслалаар тусгаарлаж бичнэ үү.',
      shortDescriptionLabel: 'Богино тайлбар',
      causeTitleLabel: 'Шалтгааны гарчиг',
      causeDescriptionLabel: 'Шалтгааны тайлбар',
      causeImageLabel: 'Дүрслэлийн тэмдэглэл',
      symptomTermLabel: 'Шинж тэмдгийн нэр томьёо',
      synonymLabel: 'Ижил утгатай нэрс',
      synonymHelp: 'Олон утгыг таслалаар тусгаарлаж бичнэ үү.',
      frequencyLabel: 'Давтамж',
      bodySystemLabel: 'Биеийн систем',
      referenceTitleLabel: 'Эх сурвалжийн гарчиг',
      referenceUrlLabel: 'Эх сурвалжийн холбоос',
      addCause: 'Шалтгаан нэмэх',
      removeCause: 'Шалтгаан хасах',
      addSymptom: 'Шинж тэмдэг нэмэх',
      removeSymptom: 'Шинж тэмдэг хасах',
      addReference: 'Эх сурвалж нэмэх',
      removeReference: 'Эх сурвалж хасах',
      toneForum: 'Форум хэв маяг',
      toneFundraiser: 'Хандивын өдөрлөг',
      toneWebinar: 'Вебинар',
      toneCalm: 'Тайван',
      toneListen: 'Сонсох',
      toneBalance: 'Тэнцвэр',
      eventCreated: 'Арга хэмжээ амжилттай нэмэгдлээ.',
      dailyCreated: 'Өдрийн булан амжилттай нэмэгдлээ.',
      diseaseCreated: 'Өвчний мэдээлэл амжилттай нэмэгдлээ.',
      eventUpdated: 'Арга хэмжээ амжилттай шинэчлэгдлээ.',
      dailyUpdated: 'Өдрийн булан амжилттай шинэчлэгдлээ.',
      diseaseUpdated: 'Өвчний мэдээлэл амжилттай шинэчлэгдлээ.',
      eventDeleted: 'Арга хэмжээ устгагдлаа.',
      dailyDeleted: 'Өдрийн булангийн бичлэг устгагдлаа.',
      diseaseDeleted: 'Өвчний мэдээлэл устгагдлаа.',
      contentPageTitle: 'Контент удирдлага',
      contentPageBody:
        'Арга хэмжээ, өдрийн булан, өвчний мэдээллүүдийг админ самбараас үүсгэж, засаж, устгана уу.',
      eventsDashboardTitle: 'Арга хэмжээний самбар',
      eventsDashboardBody: 'Нийтлэгдсэн болон ноорог арга хэмжээнүүдийг хянаж, шинэчилнэ.',
      dailyDashboardTitle: 'Өдрийн булангийн самбар',
      dailyDashboardBody: 'Өдрийн булангийн нийтлэлүүдийг огноо, төлөвтэй нь удирдана.',
      diseasesDashboardTitle: 'Өвчний мэдээллийн самбар',
      diseasesDashboardBody: 'Өвчний агуулгыг хэл, ангилал, шинэчлэлтийн төлөвтэй нь зохион байгуулна.',
      noEvents: 'Арга хэмжээ одоогоор алга байна.',
      noDailyEntries: 'Өдрийн буланд одоогоор бичлэг алга байна.',
      noDiseases: 'Өвчний мэдээлэл одоогоор алга байна.',
      editEventTitle: 'Арга хэмжээ засах',
      editDailyTitle: 'Өдрийн булан засах',
      editDiseaseTitle: 'Өвчний мэдээлэл засах',
      deleteEvent: 'Арга хэмжээ устгах',
      deleteDaily: 'Өдрийн булан устгах',
      deleteDisease: 'Өвчний мэдээлэл устгах',
      totalItems: 'Нийт',
      publishedItems: 'Нийтлэгдсэн',
      draftItems: 'Ноорог',
      statusPublished: 'Нийтлэгдсэн',
      statusDraft: 'Ноорог',
      openEditor: 'Засвар нээх',
      updatedAtLabel: 'Шинэчилсэн',
    },
    legal: {
      privacyTitle: 'Нууцлалын бодлого',
      disclaimerTitle: 'Эмнэлзүйн тайлбар, анхааруулга',
      accessibilityTitle: 'Хүртээмжийн мэдэгдэл',
    },
  },
  en: {
    siteName: 'Rare Care',
    languageLabel: 'EN',
    alternateLanguageLabel: 'MN',
    nav: {
      accessibility: 'Accessibility',
      events: 'Events',
      dailyCorner: 'Daily Corner',
      contact: 'Contact Us',
      diseaseInformation: 'Disease Information',
      community: 'Community',
      donate: 'Donate',
      searchPlaceholder: 'Search diseases...',
    },
    common: {
      home: 'Home',
      siteRegion: 'Mongolia',
      learnMore: 'Learn More',
      readNow: 'Read Now',
      joinGroup: 'Join Group',
      applyNow: 'Apply Now',
      makeDonation: 'Make Donation',
      upcomingEvents: 'Upcoming Events',
      everydayTips: 'Everyday Tips',
      educationalDisclaimer:
        'This information is educational and does not replace professional medical advice.',
      noResults: 'No matching information was found.',
      audio: 'Audio option',
      submit: 'Submit',
      sending: 'Sending...',
      search: 'Search',
      reset: 'Reset',
      other: 'Other',
      openMenu: 'Open menu',
      closeMenu: 'Close menu',
      submitError: 'There was a problem submitting the form.',
      generalError: 'Something went wrong',
      postedOn: 'Date',
      allCategories: 'All categories',
      notFound: 'Page or information not found.',
    },
    auth: {
      account: 'Account',
      login: 'Login',
      register: 'Register',
      profile: 'Profile',
      userManagement: 'User Management',
      contentManagement: 'Content Management',
      eventManagement: 'Manage Events',
      dailyCornerManagement: 'Manage Daily Corner',
      diseaseManagement: 'Manage Diseases',
      logout: 'Logout',
      signedInAs: 'Signed in as',
      welcomeTitle: 'Welcome to Rare Care',
      welcomeBody: 'Sign in to keep your place and connect with future support features in a calmer, more personal way.',
      loginTitle: 'Login',
      loginBody: 'Use your username or email and password to sign in securely.',
      registerTitle: 'Create Account',
      registerBody: 'Set up a simple account to stay connected as Rare Care grows.',
      username: 'Username',
      loginIdentifier: 'Username or email',
      loginIdentifierRequired: 'Enter your username or email.',
      name: 'Name',
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      createAccount: 'Create Account',
      close: 'Close',
      passwordHint: 'Use at least 8 characters.',
      emailRequired: 'Enter your email address.',
      emailInvalid: 'Enter a valid email address.',
      nameRequired: 'Enter your name.',
      nameMinLength: 'Name must be at least 2 characters.',
      passwordRequired: 'Enter your password.',
      passwordMinLength: 'Password must be at least 8 characters.',
      confirmPasswordRequired: 'Confirm your password.',
      passwordMismatch: 'Passwords do not match.',
      loginCta: 'Login Now',
      registerCta: 'New Account',
    },
    profile: {
      title: 'Profile',
      body: 'Review your name, picture, and account details in one calm place.',
      photoUpload: 'Upload profile photo',
      photoHelp: 'Choose an image file. Common JPG and PNG files work well.',
      photoPreview: 'Photo preview',
      removePhoto: 'Remove photo',
      photoTypeError: 'Please choose an image file.',
      photoSizeError: 'That image is too large. Please choose a file under 4MB.',
      usernameReadonly: 'Your username is currently view-only.',
      emailReadonly: 'Your email is currently view-only.',
      memberSince: 'Member since',
      save: 'Save Profile',
      success: 'Your profile was updated successfully.',
      signedOutTitle: 'Sign in to view your profile',
      signedOutBody:
        'Use the account area in the header first, then return here to manage your details.',
    },
    footer: {
      tagline:
        'A calm, trustworthy platform connecting people in Mongolia with rare disease information, emotional support, and financial assistance pathways.',
      quickLinks: 'Quick Links',
      legal: 'Legal',
      support: 'Support',
      privacy: 'Privacy Policy',
      disclaimer: 'Disclaimer',
      accessibility: 'Accessibility Statement',
    },
    home: {
      heroTitle: 'Warm, practical support for people living with rare disease.',
      heroBody:
        'Rare Care brings together reliable disease information, everyday emotional support, events, and donation pathways for Mongolian patients, caregivers, and families.',
      heroAside:
        'Reliable information, community care, and financial support pathways in one place.',
      aboutTitle: 'About Us',
      aboutBody:
        'Rare Care is designed to protect privacy, explain medical topics in clearer language, and support collaboration across families, volunteers, and clinicians.',
      helpTitle: 'How Can Rare Care Help You?',
      helpCards: [
        {
          title: 'Find Reliable Disease Information',
          body: 'Browse clear summaries, medical context, and symptom structures in one organized library.',
        },
        {
          title: 'Connect With People',
          body: 'Start with a simple, privacy-aware community area designed to expand safely later.',
        },
        {
          title: 'Apply for Financial Assistance',
          body: 'Use donation and support pathways designed to become more actionable over time.',
        },
        {
          title: 'Discover Helpful Everyday Tips',
          body: 'Read reflective guidance and emotional support content that feels calm rather than clinical.',
        },
      ],
      donationImpactTitle: 'How Your Donation Helps',
      donationImpactCards: [
        {
          icon: '♥',
          title: 'Patient Support',
          body: 'Provide financial assistance for medical-related needs and treatments.',
        },
        {
          icon: '📖',
          title: 'Information Access',
          body: 'Create and translate reliable rare disease information in Mongolian.',
        },
        {
          icon: '▣',
          title: 'Platform Development',
          body: 'Maintain and improve our platform to better serve the rare disease community.',
        },
        {
          icon: '●',
          title: 'Events & Community',
          body: 'Organize awareness campaigns, support gatherings, and community events.',
        },
      ],
      donationTrustTitle: 'Transparency & Trust',
      donationTrustBody:
        'We are committed to using all contributions responsibly and transparently. Every donation makes a meaningful impact.',
      donationHopeTitle: 'Every contribution brings hope, strength, and support.',
      donationHopeBody: 'Thank you for being part of the change.',
      donationQuote: '"We make a living by what we get, but we make a life by what we give."',
    },
    diseases: {
      listingTitle: 'Disease Information Library',
      listingBody:
        'Browse a much larger rare disease library by letter, official GARD disease category, or disease name.',
      gardReference:
        'This library is expanded using the NIH GARD disease list and browse-category structure.',
      keywordLabel: 'Keyword',
      filterLabel: 'Filter by',
      searchLabel: 'Disease name or alias',
      searchPlaceholder: 'Search by disease name, acronym, or synonym',
      categoryLabel: 'Category',
      browseByLetter: 'Browse by letter',
      browseByLetterBody: 'Jump quickly by the first letter of the disease name.',
      browseByCategory: 'Browse by disease category',
      browseByCategoryBody: 'Filter using the official GARD browse categories.',
      showingResults: 'Showing {count} diseases',
      showingRange: 'Showing {start} - {end} of {count}',
      gardSourceBadge: 'GARD',
      allLetters: 'All',
      paginationLabel: 'Disease result pages',
      previousPage: 'Previous',
      nextPage: 'Next',
      sortLabel: 'Sort',
      sortByPrefix: 'Sort by',
      sortName: 'Alphabetical',
      sortUpdated: 'Recently updated',
      aliases: 'Alternative names',
      mainDiseaseType: 'Main disease type',
      relatedDiseaseTypes: 'Related disease types',
      relatedTypeCount: '{count} more related types',
      causes: 'Causes',
      symptoms: 'Symptoms',
      atAGlance: 'At a glance',
      references: 'References',
      sourceTitle: 'Source note',
      sourceBody:
        'Rare Care indexed this entry from GARD to make browsing easier. Open the source below for fuller condition-specific details.',
      noCauseDetails: 'Detailed cause notes are not expanded on Rare Care for this entry yet.',
      noSymptomDetails: 'Detailed symptom notes are not expanded on Rare Care for this entry yet.',
      medicalSummary: 'Medical summary',
      simpleSummary: 'Simple explanation',
      symptomMedicalTerm: 'Medical term',
      symptomDescription: 'Description',
      symptomSynonyms: 'Synonyms',
      symptomFrequency: 'Frequency',
      symptomSystem: 'Body system',
      mainCauseTitle: 'Main cause',
      mainCausesTitle: 'Main causes',
      generalSymptomsGroup: 'General',
      symptomDetailsLabel: 'More details',
      symptomSearchLabel: 'Search symptoms',
      symptomSearchPlaceholder: 'Search by term, description, or synonym',
      symptomFiltersLabel: 'Filter by body system',
      symptomVisibleCount: 'Showing {count} symptoms',
      allSystems: 'All systems',
      noFilteredSymptoms:
        'No symptoms match this filter yet. Try another body system or search phrase.',
      mainSymptomsTitle: 'Main symptoms',
      quickPoints: 'Key points',
      symptomCountLabel: '{count} symptoms listed',
      symptomSystemsLabel: 'Commonly linked systems',
      variableSymptomsLabel: 'Symptoms can differ from person to person',
      multipleCategoriesLabel: 'May involve more than one body system',
      updated: 'Updated',
    },
    dailyCorner: {
      title: 'Daily Corner',
      body:
        'Daily Corner offers short, meaningful insights each day to support your emotional well-being. It provides simple reflections, encouragement, and a moment of calm whenever you need it.',
      accessibilityNote:
        'Daily Corner also supports accessibility through an optional audio feature, allowing users to listen to entries instead of reading them. This can help people who are tired, visually strained, overwhelmed, or simply more comfortable with audio-based support.',
    },
    donation: {
      title: 'Donate',
      intro:
        'Donations in Rare Care are used to support individuals living with rare diseases who face financial challenges in accessing specialized care. Contributions help improve access to reliable information, strengthen community support, and sustain a platform that connects and empowers patients across Mongolia.',
      donationType: 'Donation Type',
      oneTime: 'One-Time',
      monthly: 'Monthly',
      amount: 'Donation Amount',
      dedicateTo: 'Dedicate This Donation',
      note: 'Write Note To Us',
      yourInfo: 'Your Information',
      firstName: 'First Name',
      lastName: 'Last Name',
      address: 'Address',
      country: 'Country',
      stateProvince: 'State / Province',
      city: 'City',
      postalCode: 'Postal Code',
      email: 'Email',
      phone: 'Phone Number',
      payment: 'Payment',
      totalAmount: 'Total Donation Amount',
      paymentType: 'Payment Type',
      creditCard: 'Credit Card',
      qpay: 'QPay',
      consent:
        'I agree to the collection of my personal information for the donor section described in the Privacy Policy.',
      captcha: "I'm not a robot",
      successTitle: 'Donation saved successfully',
      successBody:
        'In development, the payment was marked successful. The payment layer is abstracted so a real gateway can be added later.',
    },
    events: {
      title: 'Events',
      body: 'Browse upcoming gatherings, webinars, and fundraising opportunities.',
      organizer: 'Organizer',
      location: 'Location',
      register: 'Register',
      posterBrand: 'Rare Care Mongolia',
      posterForum: 'Family and peer support',
      posterWebinar: 'Live online session',
      posterFundraiser: 'Community support drive',
      posterDate: 'Date',
      posterTime: 'Time',
      posterPlace: 'Place',
      registrationIntro:
        'Leave your details and we will follow up with confirmation information by email.',
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      attendees: 'Number of attendees',
      note: 'Note',
      success:
        'Your registration was saved. We will follow up with confirmation details when available.',
    },
    community: {
      title: 'Community',
      body:
        'A safe, supportive space that connects people with shared rare disease experiences, guided communication, peer knowledge, and emotional support.',
      coreIdea: 'Connection, support, and shared understanding in a safe space.',
      primaryAction: 'Post a Question',
      secondaryAction: 'Explore Support Groups',
      supportTitle: 'Reach the support you need',
      supportItems: [
        {
          icon: '♡',
          title: 'Connect With Shared Experiences',
          body: 'Find patients, caregivers, and families who understand similar rare disease journeys.',
        },
        {
          icon: '?',
          title: 'Guided Forum Communication',
          body: 'Questions can be organized by disease, topic, and need so people reach the right support faster.',
        },
        {
          icon: '✦',
          title: 'Knowledge Sharing & Peer Support',
          body: 'Share lived experience, care tips, diagnosis questions, and practical everyday guidance.',
        },
        {
          icon: '●',
          title: 'Reduce Isolation and Stigma',
          body: 'Create a sense of belonging where people feel heard, understood, and emotionally supported.',
        },
      ],
      forumTitle: 'Guided Q&A Forum',
      forumBody:
        'Search or filter by disease, topic, or need so questions become easier to find and safer to answer.',
      searchPlaceholder: 'Search questions, diseases, or topics...',
      allDiseases: 'All Diseases',
      allTopics: 'All Topics',
      groupTitle: 'Support Groups',
      groupBody: 'Browse groups by role, condition, or support need so each person can find a relevant space.',
      groups: [
        {
          role: 'Patient',
          title: 'Rare Warriors Patient Circle',
          body: 'A featured space for patients living with rare diseases to share stories, resources, and encouragement.',
          members: '14 members',
        },
        {
          role: 'Caregiver',
          title: 'Caregiver Hearts Network',
          body: 'A peer space for caregivers to exchange practical tips, emotional support, and self-care strategies.',
          members: '14 members',
        },
        {
          role: 'Family Member',
          title: 'Family Bonds Support Hub',
          body: 'A safe space for family members to find comfort, advice, and connection with others in similar situations.',
          members: '14 members',
        },
      ],
      storyTitle: 'Shared Experiences',
      storyBody: 'Stories from the community: real voices, real courage. Share with your name or anonymously.',
      shareExperience: 'Share Your Experience',
      shareExperienceTitle: 'Share Your Experience',
      shareExperienceIntro:
        'Your story can bring comfort, courage, and a feeling of not being alone. Share as much or as little as you feel comfortable with.',
      storyNameLabel: 'Name',
      storyNamePlaceholder: 'Example: Zolbayar Enkh',
      storyRoleLabel: 'Your role',
      storyRolePatient: 'Patient',
      storyRoleCaregiver: 'Caregiver',
      storyRoleFamily: 'Family member',
      storyRoleSupporter: 'Supporter',
      storyDiseaseLabel: 'Condition or context (optional)',
      storyDiseasePlaceholder: 'Example: diagnosis journey, daily care, treatment access',
      storyMessageLabel: 'Your story',
      storyMessagePlaceholder:
        "Share your experience, what helped you, what you learned, or a message of hope for someone else...",
      storyGuideTitle: 'Helpful things to include',
      storyGuideItems: [
        'One important moment in your journey',
        'Support, information, or habits that helped you',
        'Encouragement for someone with a similar experience',
        'Only details you feel safe making public',
      ],
      storyAnonymousLabel: 'Post anonymously',
      storyConsentLabel:
        'I understand this story may be visible to the community and I will avoid sharing private or sensitive details about myself or others.',
      storyCancel: 'Cancel',
      storySubmit: 'Share Story',
      storyRequired: 'Please write at least 40 characters and confirm the safety checkbox before sharing.',
      storySuccess: 'Your story was added to Shared Experiences.',
      storyAnonymousName: 'Anonymous member',
      stories: [
        {
          name: 'Zolbayar Enkh',
          role: 'Patient',
          body:
            'When I was first diagnosed, I felt completely alone. Finding others who understand this journey gives me strength to keep going.',
        },
        {
          name: 'Narantsetseg Bold',
          role: 'Caregiver',
          body:
            'Some days feel overwhelming, but connecting with others reminds me that I am not alone in this journey.',
        },
      ],
      promiseTitle: 'Safe Space Promise',
      promiseItems: [
        'Respectful, judgment-free communication',
        'Privacy-aware participation',
        'Moderated and guided discussions',
        'Support that complements, not replaces, medical care',
      ],
    },
    contact: {
      title: 'Contact Us',
      body: 'Send questions, collaboration ideas, or feedback and we will follow up when possible.',
      organization: 'Rare Care Mongolia',
      name: 'Name',
      email: 'Email',
      subject: 'Subject',
      message: 'Message',
      success: 'Your message was saved. We will follow up as soon as we can.',
    },
    admin: {
      title: 'User Management',
      body: 'Admin users can create new accounts and promote other users to admin access.',
      createTitle: 'Create New User',
      createButton: 'Create User',
      listTitle: 'Current Users',
      listBody: 'Review user accounts here and update only the admin-managed account fields.',
      detailTitle: 'User Details',
      updateTitle: 'Admin-managed account info',
      accessDeniedTitle: 'Admin access required',
      accessDeniedBody: 'Only administrator accounts can open this area.',
      createHelp: 'Assign a username, email, and password for each new account.',
      detailHelp: 'Only account-management fields can be changed here.',
      roleAdmin: 'Admin',
      roleUser: 'User',
      makeAdmin: 'Make Admin',
      created: 'The new user was created successfully.',
      promoted: 'This user now has admin access.',
      updated: 'The user account settings were updated successfully.',
      noUsers: 'No users are available yet.',
      resetPassword: 'New password',
      resetPasswordHelp: 'Leave this blank to keep the current password.',
      personalInfo: 'Personal info',
      accountInfo: 'Account info',
      openDetail: 'Open details',
      role: 'Role',
      contentStudioTitle: 'Content Studio',
      contentStudioBody:
        'Create the site’s main content in a structured way, with language, publish state, and content blocks all in one place.',
      createEventTitle: 'Create Event',
      createEventButton: 'New Event',
      createEventHelp:
        'Set up the title, schedule, organizer details, and overview for a new website event.',
      createDailyTitle: 'Create Daily Corner Entry',
      createDailyButton: 'New Daily Corner',
      createDailyHelp:
        'Prepare the daily reflection with a quote, reminder block, and optional audio link.',
      createDiseaseTitle: 'Create Disease Entry',
      createDiseaseButton: 'New Disease Info',
      createDiseaseHelp:
        'Capture the disease overview, causes, symptoms, and references in reusable content sections.',
      eventCardBody: 'Prepare the event summary, schedule, location, and related link in one place.',
      dailyCardBody: 'Publish a calmer daily entry with a title, quote, reminder, and optional audio.',
      diseaseCardBody:
        'Build out disease information with structured cause, symptom, and reference sections.',
      basicsSection: 'Basics',
      publishingSection: 'Publishing',
      detailsSection: 'Details',
      causesSection: 'Causes',
      symptomsSection: 'Symptoms',
      referencesSection: 'References',
      localeLabel: 'Language',
      publishLabel: 'Publish right away',
      summaryLabel: 'Summary',
      descriptionLabel: 'Description',
      dateLabel: 'Date',
      startTimeLabel: 'Start time',
      endTimeLabel: 'End time',
      visualToneLabel: 'Visual tone',
      visualToneHelp:
        'This changes the abstract illustration style used on the content card.',
      eventLinkLabel: 'Link',
      quoteLabel: 'Quote',
      reminderTitleLabel: 'Reminder title',
      reminderBodyLabel: 'Reminder body',
      audioUrlLabel: 'Audio URL',
      slugLabel: 'Slug',
      slugHelp: 'Leave blank to generate it from the disease name.',
      aliasesLabel: 'Alternative names',
      aliasesHelp: 'Separate multiple entries with commas.',
      shortDescriptionLabel: 'Short description',
      causeTitleLabel: 'Cause title',
      causeDescriptionLabel: 'Cause description',
      causeImageLabel: 'Visual note',
      symptomTermLabel: 'Medical term',
      synonymLabel: 'Synonyms',
      synonymHelp: 'Separate multiple entries with commas.',
      frequencyLabel: 'Frequency',
      bodySystemLabel: 'Body system',
      referenceTitleLabel: 'Reference title',
      referenceUrlLabel: 'Reference URL',
      addCause: 'Add Cause',
      removeCause: 'Remove Cause',
      addSymptom: 'Add Symptom',
      removeSymptom: 'Remove Symptom',
      addReference: 'Add Reference',
      removeReference: 'Remove Reference',
      toneForum: 'Forum',
      toneFundraiser: 'Fundraiser',
      toneWebinar: 'Webinar',
      toneCalm: 'Calm',
      toneListen: 'Listen',
      toneBalance: 'Balance',
      eventCreated: 'The event was created successfully.',
      dailyCreated: 'The Daily Corner entry was created successfully.',
      diseaseCreated: 'The disease information was created successfully.',
      eventUpdated: 'The event was updated successfully.',
      dailyUpdated: 'The Daily Corner entry was updated successfully.',
      diseaseUpdated: 'The disease information was updated successfully.',
      eventDeleted: 'The event was deleted.',
      dailyDeleted: 'The Daily Corner entry was deleted.',
      diseaseDeleted: 'The disease information was deleted.',
      contentPageTitle: 'Content Management',
      contentPageBody:
        'Create, edit, and remove Events, Daily Corner entries, and Disease Information from one admin workspace.',
      eventsDashboardTitle: 'Events Dashboard',
      eventsDashboardBody: 'Review published and draft events, then update them in place.',
      dailyDashboardTitle: 'Daily Corner Dashboard',
      dailyDashboardBody: 'Manage Daily Corner entries with their date, language, and publish state.',
      diseasesDashboardTitle: 'Disease Information Dashboard',
      diseasesDashboardBody:
        'Organize disease entries by language, category, and latest update state.',
      noEvents: 'No events are available yet.',
      noDailyEntries: 'No Daily Corner entries are available yet.',
      noDiseases: 'No disease entries are available yet.',
      editEventTitle: 'Edit Event',
      editDailyTitle: 'Edit Daily Corner Entry',
      editDiseaseTitle: 'Edit Disease Entry',
      deleteEvent: 'Delete Event',
      deleteDaily: 'Delete Daily Corner Entry',
      deleteDisease: 'Delete Disease Entry',
      totalItems: 'Total',
      publishedItems: 'Published',
      draftItems: 'Drafts',
      statusPublished: 'Published',
      statusDraft: 'Draft',
      openEditor: 'Open editor',
      updatedAtLabel: 'Updated',
    },
    legal: {
      privacyTitle: 'Privacy Policy',
      disclaimerTitle: 'Medical Disclaimer',
      accessibilityTitle: 'Accessibility Statement',
    },
  },
};

export function normalizeLocale(value: string | null | undefined): Locale {
  return value === 'en' ? 'en' : 'mn';
}

export function dictionaryFor(locale: Locale): Dictionary {
  return dictionaries[locale];
}

export function formatDisplayDate(value: string, locale: Locale): string {
  return new Intl.DateTimeFormat(locale === 'mn' ? 'mn-MN' : 'en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  }).format(new Date(value));
}

export function formatMonthDay(value: string, locale: Locale): string {
  return new Intl.DateTimeFormat(locale === 'mn' ? 'mn-MN' : 'en-US', {
    month: 'short',
    day: 'numeric',
  }).format(new Date(value));
}
